# This file is part of the doubledog-iscsi Puppet module.
# Copyright 2018 John Florian
# SPDX-License-Identifier: GPL-3.0-or-later

---

sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
matrix:
  include:
   - rvm: 2.4.1
     env: PUPPET_GEM_VERSION='~> 5.0.0' STRICT_VARIABLES=yes COVERAGE=yes
before_script:
  - bundle exec rake syntax
  - bundle exec rake lint
  - bundle exec rake metadata_lint
  - bundle exec rake validate
script:
  - bundle exec rake spec
